import Head from "next/head";
import Image from "next/image";
import { Box, Container, Typography, Button, Tooltip } from "@material-ui/core";
import React from "react";
import useMobile from "../hooks/useMobile";
import InputNumber from "../components/InputNumber";
import { users } from "../hooks/users";
import Loader from "../components/Loader";
import UserList from "../components/UserList";
import OnBoarding from "../components/OnBoarding";

export default function Home() {
  const isMobile = useMobile();
  const { usersInfo, loader } = users();
  const [openButtonTooltip, setOpenButtonTooltip] = React.useState(false);
  const [openOnBoarding, setOnBoarding] = React.useState(false);
  const firstAssessment = false;
  usersInfo?.sort(function (a: any, b: any) {
    const dateOne = new Date(b.updated_at) as any;
    const dateTwo = new Date(a.updated_at) as any;
    return dateOne - dateTwo;
  });
  const handleCloseButtonTooltip = () => {
    setOpenButtonTooltip(false);
  };

  const handleOpenButtonTooltip = () => {
    setOpenButtonTooltip(true);
  };

  if (typeof window !== "undefined") {
    if (!localStorage.getItem("onBoarding") && !openOnBoarding) {
      setOnBoarding(!localStorage.getItem("onBoarding"));
    }
  }

  return (
    <Box style={{ backgroundColor: "#efdee6", height: "100%" }}>
      <Container>
        <Head>
          <title>Dina Challenge</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {firstAssessment ? (
          <>
            <Box display="flex" alignItems="center">
              <Image
                src="/dina-logo.jpeg"
                alt="digital-natives"
                width={100}
                height={100}
              />
              <Box marginLeft={isMobile ? 1 : 12}>
                {isMobile ? (
                  <Typography variant="h6">
                    Arabic number conversion tool
                  </Typography>
                ) : (
                  <Typography variant="h3">
                    Arabic number conversion tool
                  </Typography>
                )}
              </Box>
            </Box>
            <Box display="flex" flexDirection="column" alignItems="center">
              <InputNumber />
            </Box>
          </>
        ) : (
          <>
            <Box display="flex" alignItems="center" margin="0">
              <Image
                src="/dina-logo.jpeg"
                alt="digital-natives"
                width={100}
                height={100}
              />
              <Box marginLeft={isMobile ? 1 : 12}>
                <Typography variant="h3" style={{ fontStyle: "italic" }}>
                  User`s List
                </Typography>
              </Box>
            </Box>
            <Box display="flex" justifyContent="flex-end" pb={1}>
              <Tooltip
                open={openButtonTooltip}
                onClose={handleCloseButtonTooltip}
                onOpen={handleOpenButtonTooltip}
                title="Create new user"
              >
                <Button variant="contained" color="secondary" href="./new">
                  Create user
                </Button>
              </Tooltip>
            </Box>
            {loader ? (
              <Loader />
            ) : (
              <Box
                display="flex"
                justifyContent="center"
                style={{ boxShadow: "1px -2px 50px -20px #000000" }}
              >
                <UserList userList={usersInfo} />
              </Box>
            )}
          </>
        )}
        {openOnBoarding ? <OnBoarding /> : ""}
      </Container>
    </Box>
  );
}
