import React, { useEffect, useState } from "react";
import TextField from "@material-ui/core/TextField";
import { makeStyles } from "@material-ui/core/styles";
import { Box, Container, Typography } from "@material-ui/core";
import { User } from "../model/user";
import UserForm from "../components/UserForm";
import Head from "next/head";
import Image from "next/image";
import useMobile from "../hooks/useMobile";

interface Props {
  initialData: User;
}

const useStyles = makeStyles((theme) => ({
  root: {
    "& .MuiTextField-root": {
      margin: theme.spacing(1),
      width: "25ch",
    },
  },
}));

const NewUserForm: React.FC<Props> = ({ initialData }) => {

  return (
    <Box>
      <Container>
        <Head>
          <title>Dina Challenge</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box display="flex" alignItems="center" margin="0">
          <Image
            src="/dina-logo.jpeg"
            alt="digital-natives"
            width={100}
            height={100}
          />
        </Box>
        <Box>
          <Box
            display="flex"
            justifyContent="space-around"
            top="40%"
            margin={0}
            position="absolute"
            
          >
            <Box display="flex" justifyContent="center">
              <Typography variant="h3">New user</Typography>
            </Box>
            <UserForm initialData={initialData} isNew={true} />
          </Box>
        </Box>
      </Container>
    </Box>
  );
};
export default NewUserForm;
